export const DISEASE_LIST_REQUEST = 'DISEASE_LIST_REQUEST'
export const DISEASE_LIST_SUCCESS = 'DISEASE_LIST_SUCCESS'
export const DISEASE_LIST_FAIL = 'DISEASE_LIST_FAIL'

export const DISEASE_REQUEST = 'DISEASE_REQUEST'
export const DISEASE_SUCCESS = 'DISEASE_SUCCESS'
export const DISEASE_FAIL = 'DISEASE_FAIL'

export const PATIENT_DISEASE_LIST_REQUEST = 'PATIENT_DISEASE_LIST_REQUEST'
export const PATIENT_DISEASE_LIST_SUCCESS = 'PATIENT_DISEASE_LIST_SUCCESS'
export const PATIENT_DISEASE_LIST_FAIL = 'PATIENT_DISEASE_LIST_FAIL'

export const DISEASE_CREATE_REQUEST = 'DISEASE_CREATE_REQUEST'
export const DISEASE_CREATE_SUCCESS = 'DISEASE_CREATE_SUCCESS'
export const DISEASE_CREATE_FAIL = 'DISEASE_CREATE_FAIL'
export const DISEASE_CREATE_RESET = 'DISEASE_CREATE_RESET'

export const DISEASE_DELETE_REQUEST = 'DISEASE_DELETE_REQUEST'
export const DISEASE_DELETE_SUCCESS = 'DISEASE_DELETE_SUCCESS'
export const DISEASE_DELETE_FAIL = 'DISEASE_DELETE_FAIL'

export const DISEASE_UPDATE_REQUEST = 'DISEASE_UPDATE_REQUEST'
export const DISEASE_UPDATE_SUCCESS = 'DISEASE_UPDATE_SUCCESS'
export const DISEASE_UPDATE_FAIL = 'DISEASE_UPDATE_FAIL'
export const DISEASE_UPDATE_RESET = 'DISEASE_UPDATE_RESET'
