export const DISEASE_LIST_REQUEST = 'DISEASE_LIST_REQUEST'
export const DISEASE_LIST_SUCCESS = 'DISEASE_LIST_SUCCESS'
export const DISEASE_LIST_FAIL = 'DISEASE_LIST_FAIL'

export const PATIENT_DISEASE_LIST_REQUEST = 'PATIENT_DISEASE_LIST_REQUEST'
export const PATIENT_DISEASE_LIST_SUCCESS = 'PATIENT_DISEASE_LIST_SUCCESS'
export const PATIENT_DISEASE_LIST_FAIL = 'PATIENT_DISEASE_LIST_FAIL'
