export const DOCTOR_LOGIN_REQUEST = 'DOCTOR_LOGIN_REQUEST'
export const DOCTOR_LOGIN_SUCCESS = 'DOCTOR_LOGIN_SUCCESS'
export const DOCTOR_LOGIN_FAIL = 'DOCTOR_LOGIN_FAIL'
export const DOCTOR_LOGOUT = 'DOCTOR_LOGOUT'

export const DOCTOR_REGISTER_REQUEST = 'DOCTOR_REGISTER_REQUEST'
export const DOCTOR_REGISTER_SUCCESS = 'DOCTOR_REGISTER_SUCCESS'
export const DOCTOR_REGISTER_FAIL = 'DOCTOR_REGISTER_FAIL'

export const DOCTOR_DETAILS_REQUEST = 'DOCTOR_DETAILS_REQUEST'
export const DOCTOR_DETAILS_SUCCESS = 'DOCTOR_DETAILS_SUCCESS'
export const DOCTOR_DETAILS_FAIL = 'DOCTOR_DETAILS_FAIL'
export const DOCTOR_DETAILS_RESET = 'DOCTOR_DETAILS_RESET'

export const DOCTOR_UPDATE_PROFILE_REQUEST = 'DOCTOR_UPDATE_PROFILE_REQUEST'
export const DOCTOR_UPDATE_PROFILE_SUCCESS = 'DOCTOR_UPDATE_PROFILE_SUCCESS'
export const DOCTOR_UPDATE_PROFILE_FAIL = 'DOCTOR_UPDATE_PROFILE_FAIL'
export const DOCTOR_UPDATE_PROFILE_RESET = 'DOCTOR_UPDATE_PROFILE_RESET'
