export const DOCTOR_LOGIN_REQUEST = 'DOCTOR_LOGIN_REQUEST'
export const DOCTOR_LOGIN_SUCCESS = 'DOCTOR_LOGIN_SUCCESS'
export const DOCTOR_LOGIN_FAIL = 'DOCTOR_LOGIN_FAIL'
export const DOCTOR_LOGOUT = 'DOCTOR_LOGOUT'
