export const PATIENT_LIST_REQUEST = 'PATIENT_LIST_REQUEST'
export const PATIENT_LIST_SUCCESS = 'PATIENT_LIST_SUCCESS'
export const PATIENT_LIST_FAIL = 'PATIENT_LIST_FAIL'

export const PATIENT_REQUEST = 'PATIENT_REQUEST'
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS'
export const PATIENT_FAIL = 'PATIENT_FAIL'

export const PATIENT_BY_DISEASE_LIST_REQUEST = 'PATIENT_BY_DISEASE_LIST_REQUEST'
export const PATIENT_BY_DISEASE_LIST_SUCCESS = 'PATIENT_BY_DISEASE_LIST_SUCCESS'
export const PATIENT_BY_DISEASE_LIST_FAIL = 'PATIENT_BY_DISEASE_LIST_FAIL'

export const PATIENT_AND_DISEASE_LIST_REQUEST =
  'PATIENT_AND_DISEASE_LIST_REQUEST'
export const PATIENT_AND_DISEASE_LIST_SUCCESS =
  'PATIENT_AND_DISEASE_LIST_SUCCESS'
export const PATIENT_AND_DISEASE_LIST_FAIL = 'PATIENT_AND_DISEASE_LIST_FAIL'

export const PATIENT_CREATE_REQUEST = 'PATIENT_CREATE_REQUEST'
export const PATIENT_CREATE_SUCCESS = 'PATIENT_CREATE_SUCCESS'
export const PATIENT_CREATE_FAIL = 'PATIENT_CREATE_FAIL'
