export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'
export const QUESTION_CREATE_RESET = 'QUESTION_CREATE_RESET'

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL'

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST'
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS'
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL'
export const QUESTION_UPDATE_RESET = 'QUESTION_UPDATE_RESET'
