export const PATIENT_RESPONSE_LIST_REQUEST = 'PATIENT_RESPONSE_LIST_REQUEST'
export const PATIENT_RESPONSE_LIST_SUCCESS = 'PATIENT_RESPONSE_LIST_SUCCESS'
export const PATIENT_RESPONSE_LIST_FAIL = 'PATIENT_RESPONSE_LIST_FAIL'

export const PATIENTS_RESPONSE_LIST_REQUEST = 'PATIENTS_RESPONSE_LIST_REQUEST'
export const PATIENTS_RESPONSE_LIST_SUCCESS = 'PATIENTS_RESPONSE_LIST_SUCCESS'
export const PATIENTS_RESPONSE_LIST_FAIL = 'PATIENTS_RESPONSE_LIST_FAIL'

export const PATIENTS_STUDY_RESPONSE_LIST_REQUEST =
  'PATIENTS_STUDY_RESPONSE_LIST_REQUEST'
export const PATIENTS_STUDY_RESPONSE_LIST_SUCCESS =
  'PATIENTS_STUDY_RESPONSE_LIST_SUCCESS'
export const PATIENTS_STUDY_RESPONSE_LIST_FAIL =
  'PATIENTS_STUDY_RESPONSE_LIST_FAIL'
