export const PATIENT_RESPONSE_LIST_REQUEST = 'PATIENT_RESPONSE_LIST_REQUEST'
export const PATIENT_RESPONSE_LIST_SUCCESS = 'PATIENT_RESPONSE_LIST_SUCCESS'
export const PATIENT_RESPONSE_LIST_FAIL = 'PATIENT_RESPONSE_LIST_FAIL'
