export const SENSOR_LIST_REQUEST = 'SENSOR_LIST_REQUEST'
export const SENSOR_LIST_SUCCESS = 'SENSOR_LIST_SUCCESS'
export const SENSOR_LIST_FAIL = 'SENSOR_LIST_FAIL'

export const SENSOR_CREATE_REQUEST = 'SENSOR_CREATE_REQUEST'
export const SENSOR_CREATE_SUCCESS = 'SENSOR_CREATE_SUCCESS'
export const SENSOR_CREATE_FAIL = 'SENSOR_CREATE_FAIL'

export const SENSOR_ENABLE_REQUEST = 'SENSOR_ENABLE_REQUEST'
export const SENSOR_ENABLE_SUCCESS = 'SENSOR_ENABLE_SUCCESS'
export const SENSOR_ENABLE_FAIL = 'SENSOR_ENABLE_FAIL'

export const SENSOR_DELETE_REQUEST = 'SENSOR_DELETE_REQUEST'
export const SENSOR_DELETE_SUCCESS = 'SENSOR_DELETE_SUCCESS'
export const SENSOR_DELETE_FAIL = 'SENSOR_DELETE_FAIL'

export const SENSOR_UPDATE_REQUEST = 'SENSOR_UPDATE_REQUEST'
export const SENSOR_UPDATE_SUCCESS = 'SENSOR_UPDATE_SUCCESS'
export const SENSOR_UPDATE_FAIL = 'SENSOR_UPDATE_FAIL'
