export const STUDY_LIST_REQUEST = 'STUDY_LIST_REQUEST'
export const STUDY_LIST_SUCCESS = 'STUDY_LIST_SUCCESS'
export const STUDY_LIST_FAIL = 'STUDY_LIST_FAIL'

export const STUDY_CREATE_REQUEST = 'STUDY_CREATE_REQUEST'
export const STUDY_CREATE_SUCCESS = 'STUDY_CREATE_SUCCESS'
export const STUDY_CREATE_FAIL = 'STUDY_CREATE_FAIL'
export const STUDY_CREATE_RESET = 'STUDY_CREATE_RESET'

export const STUDY_DELETE_REQUEST = 'STUDY_DELETE_REQUEST'
export const STUDY_DELETE_SUCCESS = 'STUDY_DELETE_SUCCESS'
export const STUDY_DELETE_FAIL = 'STUDY_DELETE_FAIL'
