export const STUDY_LIST_REQUEST = 'STUDY_LIST_REQUEST'
export const STUDY_LIST_SUCCESS = 'STUDY_LIST_SUCCESS'
export const STUDY_LIST_FAIL = 'STUDY_LIST_FAIL'

export const STUDY_CREATE_REQUEST = 'STUDY_CREATE_REQUEST'
export const STUDY_CREATE_SUCCESS = 'STUDY_CREATE_SUCCESS'
export const STUDY_CREATE_FAIL = 'STUDY_CREATE_FAIL'
export const STUDY_CREATE_RESET = 'STUDY_CREATE_RESET'

export const STUDY_DELETE_REQUEST = 'STUDY_DELETE_REQUEST'
export const STUDY_DELETE_SUCCESS = 'STUDY_DELETE_SUCCESS'
export const STUDY_DELETE_FAIL = 'STUDY_DELETE_FAIL'

export const STUDY_UPDATE_REQUEST = 'STUDY_UPDATE_REQUEST'
export const STUDY_UPDATE_SUCCESS = 'STUDY_UPDATE_SUCCESS'
export const STUDY_UPDATE_FAIL = 'STUDY_UPDATE_FAIL'
export const STUDY_UPDATE_RESET = 'STUDY_UPDATE_RESET'

export const PATIENTS_BY_STUDY_LIST_REQUEST = 'PATIENTS_BY_STUDY_LIST_REQUEST'
export const PATIENTS_BY_STUDY_LIST_SUCCESS = 'PATIENTS_BY_STUDY_LIST_SUCCESS'
export const PATIENTS_BY_STUDY_LIST_FAIL = 'PATIENTS_BY_STUDY_LIST_FAIL'
