export const SURVEY_TEMPLATE_LIST_REQUEST = 'SURVEY_TEMPLATE_LIST_REQUEST'
export const SURVEY_TEMPLATE_LIST_SUCCESS = 'SURVEY_TEMPLATE_LIST_SUCCESS'
export const SURVEY_TEMPLATE_LIST_FAIL = 'SURVEY_TEMPLATE_LIST_FAIL'

export const SURVEY_CREATE_TEMPLATE_REQUEST = 'SURVEY_CREATE_TEMPLATE_REQUEST'
export const SURVEY_CREATE_TEMPLATE_SUCCESS = 'SURVEY_CREATE_TEMPLATE_SUCCESS'
export const SURVEY_CREATE_TEMPLATE_FAIL = 'SURVEY_CREATE_TEMPLATE_FAIL'

export const SURVEY_REQUEST = 'SURVEY_REQUEST'
export const SURVEY_SUCCESS = 'SURVEY_SUCCESS'
export const SURVEY_FAIL = 'SURVEY_FAIL'

export const SURVEY_SAVE_ID_REQUEST = 'SURVEY_SAVE_ID_REQUEST'
export const SURVEY_SAVE_ID_RESET = 'SURVEY_SAVE_ID_RESET'

export const SURVEY_CREATE_REQUEST = 'SURVEY_CREATE_REQUEST'
export const SURVEY_CREATE_SUCCESS = 'SURVEY_CREATE_SUCCESS'
export const SURVEY_CREATE_FAIL = 'SURVEY_CREATE_FAIL'

export const SURVEY_CURRENT_REQUEST = 'SURVEY_CURRENT_REQUEST'
export const SURVEY_CURRENT_SUCCESS = 'SURVEY_CURRENT_SUCCESS'
export const SURVEY_CURRENT_FAIL = 'SURVEY_CURRENT_FAIL'

export const SURVEY_PATIENT_ASSIGNMENT_REQUEST =
  'SURVEY_PATIENT_ASSIGNMENT_REQUEST'
export const SURVEY_PATIENT_ASSIGNMENT_SUCCESS =
  'SURVEY_PATIENT_ASSIGNMENT_SUCCESS'
export const SURVEY_PATIENT_ASSIGNMENT_FAIL = 'SURVEY_PATIENT_ASSIGNMENT_FAIL'

export const SURVEY_ASSIGNED_BY_DOCTOR_REQUEST =
  'SURVEY_ASSIGNED_BY_DOCTOR_REQUEST'
export const SURVEY_ASSIGNED_BY_DOCTOR_SUCCESS =
  'SURVEY_ASSIGNED_BY_DOCTOR_SUCCESS'
export const SURVEY_ASSIGNED_BY_DOCTOR_FAIL = 'SURVEY_ASSIGNED_BY_DOCTOR_FAIL'

export const SURVEY_ASSIGNED_REQUEST = 'SURVEY_ASSIGNED_REQUEST'
export const SURVEY_ASSIGNED_SUCCESS = 'SURVEY_ASSIGNED_SUCCESS'
export const SURVEY_ASSIGNED_FAIL = 'SURVEY_ASSIGNED_FAIL'

export const SURVEY_ASSIGNED_WITH_PATIENT_REQUEST =
  'SURVEY_ASSIGNED_WITH_PATIENT_REQUEST'
export const SURVEY_ASSIGNED_WITH_PATIENT_SUCCESS =
  'SURVEY_ASSIGNED_WITH_PATIENT_SUCCESS'
export const SURVEY_ASSIGNED_WITH_PATIENT_FAIL =
  'SURVEY_ASSIGNED_WITH_PATIENT_FAIL'

export const SURVEY_DELETE_REQUEST = 'SURVEY_DELETE_REQUEST'
export const SURVEY_DELETE_SUCCESS = 'SURVEY_DELETE_SUCCESS'
export const SURVEY_DELETE_FAIL = 'SURVEY_DELETE_FAIL'
