export const SURVEY_TEMPLATE_LIST_REQUEST = 'SURVEY_TEMPLATE_LIST_REQUEST'
export const SURVEY_TEMPLATE_LIST_SUCCESS = 'SURVEY_TEMPLATE_LIST_SUCCESS'
export const SURVEY_TEMPLATE_LIST_FAIL = 'SURVEY_TEMPLATE_LIST_FAIL'
