export const SURVEY_TEMPLATE_LIST_REQUEST = 'SURVEY_TEMPLATE_LIST_REQUEST'
export const SURVEY_TEMPLATE_LIST_SUCCESS = 'SURVEY_TEMPLATE_LIST_SUCCESS'
export const SURVEY_TEMPLATE_LIST_FAIL = 'SURVEY_TEMPLATE_LIST_FAIL'

export const SURVEY_CREATE_TEMPLATE_REQUEST = 'SURVEY_CREATE_TEMPLATE_REQUEST'
export const SURVEY_CREATE_TEMPLATE_SUCCESS = 'SURVEY_CREATE_TEMPLATE_SUCCESS'
export const SURVEY_CREATE_TEMPLATE_FAIL = 'SURVEY_CREATE_TEMPLATE_FAIL'

export const SURVEY_REQUEST = 'SURVEY_REQUEST'
export const SURVEY_SUCCESS = 'SURVEY_SUCCESS'
export const SURVEY_FAIL = 'SURVEY_FAIL'

export const SURVEY_SAVE_ID_REQUEST = 'SURVEY_SAVE_ID_REQUEST'
export const SURVEY_SAVE_ID_RESET = 'SURVEY_SAVE_ID_RESET'

export const SURVEY_CREATE_REQUEST = 'SURVEY_CREATE_REQUEST'
export const SURVEY_CREATE_SUCCESS = 'SURVEY_CREATE_SUCCESS'
export const SURVEY_CREATE_FAIL = 'SURVEY_CREATE_FAIL'
