export const SURVEY_TIME_SLOT_REQUEST = 'SURVEY_TIME_SLOT_REQUEST'
export const SURVEY_TIME_SLOT_SUCCESS = 'SURVEY_TIME_SLOT_SUCCESS'
export const SURVEY_TIME_SLOT_FAIL = 'SURVEY_TIME_SLOT_FAIL'

export const UPDATE_TIME_SLOT_REQUEST = 'UPDATE_TIME_SLOT_REQUEST'
export const UPDATE_TIME_SLOT_SUCCESS = 'UPDATE_TIME_SLOT_SUCCESS'
export const UPDATE_TIME_SLOT_FAIL = 'UPDATE_TIME_SLOT_FAIL'
